sonar.projectKey=mediation
sonar.projectName=mediation
sonar.sources=.
sonar.exclusions=**/vendor/**,**/node_modules/**,**/*.min.js,**/*.min.css,**/storage/**,**/bootstrap/cache/**,**/public/**
sonar.sourceEncoding=UTF-8